/// Bot-ready prompt service architecture.
///
/// [PromptService] is the abstract interface that all prompt providers must
/// implement.  Today, [StaticPromptService] fulfills this with the hard-coded
/// contemplative prompts defined in [StepTraditionContent].
///
/// When the AI recovery-bot feature ships, create a class that extends
/// [PromptService] (e.g. `AiPromptService`) and override the
/// [promptServiceProvider] in your ProviderScope:
///
/// ```dart
/// ProviderScope(
///   overrides: [
///     promptServiceProvider.overrideWith((ref) => AiPromptService(ref)),
///   ],
///   child: MyApp(),
/// )
/// ```
///
/// No other code needs to change — every screen already reads prompts
/// through [promptServiceProvider].

import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../data/step_tradition_content.dart';

// ─────────────────────────────────────────────────────────────────────────────
// Model
// ─────────────────────────────────────────────────────────────────────────────

/// Origin of a contemplative prompt.
enum PromptSource {
  /// Built-in, curated static prompt (current implementation).
  static,

  /// AI-generated by the recovery bot (future implementation).
  ai,
}

/// A single writing prompt for a step or tradition.
class ContemplativePrompt {
  /// Stable identifier, e.g. "step_1_0", "tradition_3_2".
  /// Stored in [JournalEntry.promptId] when an entry is inspired by a prompt.
  final String id;

  /// The prompt text shown to the user.
  final String text;

  /// Where this prompt came from.
  final PromptSource source;

  const ContemplativePrompt({
    required this.id,
    required this.text,
    this.source = PromptSource.static,
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// Abstract interface
// ─────────────────────────────────────────────────────────────────────────────

abstract class PromptService {
  /// Returns contemplative writing prompts for [stepNumber] (1–12).
  /// Returns an empty list if the step number is invalid.
  List<ContemplativePrompt> getPromptsForStep(int stepNumber);

  /// Returns contemplative writing prompts for [traditionNumber] (1–12).
  /// Returns an empty list if the tradition number is invalid.
  List<ContemplativePrompt> getPromptsForTradition(int traditionNumber);

  /// Returns prompts for any [JournalSubjectContent].
  List<ContemplativePrompt> getPrompts(JournalSubjectContent content) {
    return content.type == JournalSubjectType.step
        ? getPromptsForStep(content.number)
        : getPromptsForTradition(content.number);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Static implementation
// ─────────────────────────────────────────────────────────────────────────────

/// Returns the curated prompts embedded in [StepTraditionContent].
/// This is the default implementation; replace with [AiPromptService]
/// once the recovery-bot feature is ready.
class StaticPromptService extends PromptService {
  // ignore: prefer_const_constructors_in_immutables
  StaticPromptService();

  @override
  List<ContemplativePrompt> getPromptsForStep(int stepNumber) {
    final content = StepTraditionContent.forStep(stepNumber);
    if (content == null) return const [];
    return _buildPrompts('step_$stepNumber', content.contemplativePrompts);
  }

  @override
  List<ContemplativePrompt> getPromptsForTradition(int traditionNumber) {
    final content = StepTraditionContent.forTradition(traditionNumber);
    if (content == null) return const [];
    return _buildPrompts(
        'tradition_$traditionNumber', content.contemplativePrompts);
  }

  List<ContemplativePrompt> _buildPrompts(
      String prefix, List<String> texts) {
    return texts.asMap().entries.map((entry) {
      return ContemplativePrompt(
        id: '${prefix}_${entry.key}',
        text: entry.value,
        source: PromptSource.static,
      );
    }).toList();
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Provider
// ─────────────────────────────────────────────────────────────────────────────

/// Override this provider with [AiPromptService] when the recovery bot
/// is integrated.
final promptServiceProvider = Provider<PromptService>((ref) {
  return StaticPromptService();
});
