import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:drift/drift.dart';
// Paths adjusted to go up three levels to reach the root lib folder
import '../../../data/repositories/amends_repository.dart';
import '../../../core/database/database.dart';

// Provides the real-time list of all amends
// 'Amend' is the data class generated by Drift from the 'Amends' table
final amendsListProvider = StreamProvider<List<Amend>>((ref) {
  return ref.watch(amendsRepositoryProvider).watchAll();
});

// Logic to toggle completion status in the database
final amendsUpdateProvider = Provider((ref) {
  // Ensure databaseProvider is defined in core/database/database.dart
  final db = ref.watch(databaseProvider); 
  
  return (int id, bool isCompleted) async {
    await (db.update(db.amends)..where((t) => t.id.equals(id))).write(
      AmendsCompanion(
        status: Value(isCompleted ? 'Completed' : 'Planned'),
      ),
    );
  };
});